baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Mysticetus"

# assetDir = "static/img"

googleAnalytics = ""

ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[[menu.main]]
  name = "Industries"
  url = "/industry/"
  weight = 1
  identifier = "industries"
[[menu.main]]
  name = "Energy"
  url = "/industry/energy/"
  weight = 1
  parent = "industries"
[[menu.main]]
  name = "PSO Providers"
  url = "/industry/pso-provider/"
  weight = 2
  parent = "industries"
[[menu.main]]
  name = "Academia"
  url = "/industry/academia/"
  weight = 3
  parent = "industries"

[[menu.main]]
  name = "Product"
  url = "/product/"
  weight = 2

[[menu.main]]
  name = "Company"
  url = "/company/"
  weight = 3
	identifier = "company"
[[menu.main]]
  name = "About"
  url = "/company/about/"
  weight = 1
  parent = "company"
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 2
  parent = "company"

# [[menu.main]]
#   name = "Pricing"
#   url = "/pricing/"
#   weight = 4

[[menu.footer]]
	identifier = "mysticetus"
	name = "Mysticetus"
	weight = 1
[[menu.footer]]
	name = "Energy"
	url = "/industry/energy/"
	weight = 1
	parent = "mysticetus"
[[menu.footer]]
	name = "PSO Providers"
	url = "/industry/pso-provider/"
	weight = 2
	parent = "mysticetus"
[[menu.footer]]
	name = "Academia"
	url = "/industry/academia/"
	weight = 3
	parent = "mysticetus"
[[menu.footer]]
	name = "----"
	weight = 5
	parent= "mysticetus"
[[menu.footer]]
	name = "Request a Demo"
	url = "/demo/"
	weight = 6
	parent = "mysticetus"
# [[menu.footer]]
# 	name = "Pricing"
# 	url = "/pricing/"
# 	weight = 5
# 	parent = "mysticetus"

[[menu.footer]]
	identifier = "resources"
	name = "Resource"
	weight = 2
[[menu.footer]]
	name = "Features"
	url = "/product/"
	weight = 1
	parent = "resources"
[[menu.footer]]
	name="Help"
	url = "/contact/"
	weight = 2
	parent = "resources"
# [[menu.footer]]
# 	name="Privacy"
# 	url = "/privacy/"
# 	weight = 2
# 	parent = "resources"
# [[menu.footer]]
# 	name="Terms & Use"
# 	url = "/terms/"
# 	weight = 3
# 	parent = "resources"
# [[menu.footer]]
# 	name="Security"
# 	url = "/security/"
# 	weight = 4
# 	parent = "resources"

[[menu.footer]]
	identifier = "company"
	name = "Company"
	weight = 3
[[menu.footer]]
	name = "About"
	url = "/about/"
	weight = 1
	parent = "company"
[[menu.footer]]
	name = "Contact"
	url = "/contact/"
	weight = 2
	parent = "company"

[taxonomy]
	industry = "industry"

[params]
	logo = "/img/mysticetus.png"
	fullName = "Mysticetus, LLC."
  background = "/img/bg11.jpg"
  tint = "orange"
  custom_css = []
  custom_js = []
  date_format = "Mon, Jan 2, 2006"
  description = "A website built through Hugo for Mysticetus."
	cta_text = "Request a Demo"
	footerLogo = "/img/mysticetus.png"
	footerText = "Mysticetus ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper."
	slugs = ["industry", "energy"]